server:
  port: ${PORT:31001}
spring:
  application:
    name: xc-service-manage-cms
  data:
    mongodb:
      uri:  mongodb://localhost:27017
      database: xc_cms
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtualHost: /
  freemarker:
    cache: false  #关闭模板缓存，方便测试
    settings:
      template_update_delay: 0

  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/xc_course1?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8


eureka:
  client:
    register-with-eureka: true #服务注册,是否将自己注册到服务中
    fetch-registry: true #服务发现,是否从eureka中获取注册信息
    service-url:
      defaultZone: ${EUREKA_SEVER:http://localhost:50101/eureka/}
  instance:
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
    ip-address: ${IP_ADDRESS:127.0.0.1}
    instance-id: ${spring.application.name}-${server.port}
