server:
  port: 31450
spring:
  application:
    name: xc-service-manage-media-processor
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/xc_course1?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
  data:
    mongodb:
      uri:  mongodb://localhost:27017
      database: xc_media
#rabbitmq配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
xc-service-manage-media:
  mq:
    queue-media-video-processor: queue_media_video_processor
    routingkey-media-video: routingkey_media_video
  video-location: D:/develop/video/
  ffmpeg-path: D:/app/ffmpeg/ffmpeg-20190623-ffa64a4-win64-static/bin/ffmpeg.exe
